# Generated by Django 5.2.7 on 2025-11-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('duracao', models.CharField(blank=True, max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
