# Generated by Django 5.2.7 on 2025-11-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='modulos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
