# Generated by Django 5.2.7 on 2025-11-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
