# Generated by Django 5.2.7 on 2025-11-14 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_usuario_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
